import { energyNodeConfig } from './energyNodeConfig';

export interface HowToPlayImage {
  textureKey: string; // must already be loaded/generated by BootScene -- see BootScene.ts's preload()/create()
  label: string;
  // Overrides howToPlayConfig.imageMaxSizePx's shared fit-to-box sizing for
  // this one image (aspect still preserved, see HowToPlayScene.renderPage())
  // -- for a pickup like the Energy Node, showing it at its authored
  // gameplay display size (not scaled up to fill the same box as a
  // stationary object like a wormhole) avoids misrepresenting how big it
  // reads in-level (2026-08-27, user report after playtesting: it "looks
  // MUCH larger on this screen").
  displaySizePx?: number;
}

export interface HowToPlayPage {
  title: string;
  body: string;
  images: HowToPlayImage[];
  // Draws a '->' between each adjacent image pair (HowToPlayScene.ts) --
  // only meaningful when images represents an ordered sequence of steps,
  // like Probe -> Relay Beacon -> Wormhole below. Omitted/false for pages
  // like "Energy & Resupply" where the images are parallel concepts, not
  // steps.
  showSequenceArrows?: boolean;
}

// Page content for HowToPlayScene. Images reuse already-loaded/generated
// in-game textures (BootScene.ts) rather than new UI art, per the user's
// request -- HowToPlayScene scales each down to fit, aspect preserved (see
// howToPlayConfig.ts's imageMaxSizePx).
//
// Deliberately just an array -- adding a future "Abilities" or "Hazards"
// page (docs/history/... not yet written; discussed 2026-08-27) is only a
// matter of appending another HowToPlayPage entry here, no Scene changes
// needed. Not built yet: those two pages need their own per-item copy
// (probably keyed off abilityUnlockContent.ts and hazardConfig.ts) and
// weren't asked for in this pass.
export const howToPlayPages: HowToPlayPage[] = [
  {
    title: 'The Core Loop',
    body:
      "Launch from the Entry Wormhole and explore the level -- scan asteroids, dodge hazards, and track down the level's inactive Probe. Once you've recovered it, head for the Relay Beacon. Reaching the beacon opens the Exit Wormhole, a separate location from where you started -- return through it to complete the expedition.",
    images: [
      { textureKey: 'probe', label: 'Probe' },
      { textureKey: 'relay_beacon', label: 'Relay Beacon' },
      { textureKey: 'wormhole', label: 'Wormhole' },
    ],
    showSequenceArrows: true,
  },
  {
    title: 'Energy & Resupply',
    body:
      'Energy powers your abilities and trickles back on its own -- collect glowing Energy Nodes scattered around the level for a quick recharge. Structure is your hull integrity: hazards chip away at it, and running out forces a restart. Dock at an Asteroid Field to repair your structure back up.',
    images: [
      // Radius*2, not howToPlayConfig.imageMaxSizePx -- see displaySizePx's
      // doc comment above.
      { textureKey: 'energy_node_glow', label: 'Energy Node', displaySizePx: energyNodeConfig.radius * 2 },
      { textureKey: 'asteroid_large', label: 'Asteroid Field' },
    ],
  },
];
